library(lubridate)
tab1<-read.table("household_power_consumption.txt",sep=';',header = TRUE,dec = '.')
tab1<-subset(tab1,Date %in% c('1/2/2007','2/2/2007'))
tab1$Sub_metering_1<-as.numeric(tab1$Sub_metering_1)
tab1$Sub_metering_2<-as.numeric(tab1$Sub_metering_2)
tab1$Datetime<-dmy_hms(paste(tab1$Date,tab1$Time))
#Saving plot png file 
png(filename = "plot3.png",width = 480,height = 480,units = "px")
plot(tab1$Datetime,tab1$Sub_metering_1,type='l',col="black",ylab = "Energy Submetering",xlab = " ")
lines(tab1$Datetime,tab1$Sub_metering_2,type='l',col="red")
lines(tab1$Datetime,tab1$Sub_metering_3,type='l',col="blue")
legend("topright",lty=1,lwd=2.5,col=c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()