library(lubridate)
tab1<-read.table("household_power_consumption.txt",sep=';',header = TRUE,dec = '.')
tab1<-subset(tab1,Date %in% c('1/2/2007','2/2/2007'))
tab1$Global_active_power<-as.numeric(tab1$Global_active_power)
tab1$Global_reactive_power<-as.numeric(tab1$Global_reactive_power)
tab1$Voltage<-as.numeric(tab1$Voltage)
tab1$Sub_metering_1<-as.numeric(tab1$Sub_metering_1)
tab1$Sub_metering_2<-as.numeric(tab1$Sub_metering_2)
tab1$Datetime<-dmy_hms(paste(tab1$Date,tab1$Time))
#Saving plot png file 
png(filename = "plot4.png",width = 480,height = 480,units = "px")
par(mfrow=c(2,2))
plot(tab1$Datetime,tab1$Global_active_power,type='l',ylab = "Global Active Power(kilowatts)",xlab=" ")
plot(tab1$Datetime,tab1$Voltage,type='l',ylab = "Voltage",xlab=" ")
plot(tab1$Datetime,tab1$Sub_metering_1,type='l',col="black",ylab = "Energy Submetering",xlab = " ")
lines(tab1$Datetime,tab1$Sub_metering_2,type='l',col="red")
lines(tab1$Datetime,tab1$Sub_metering_3,type='l',col="blue")
legend("topright",lty=1,lwd=2.5,col=c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(tab1$Datetime,tab1$Global_reactive_power,type='l',ylab = "Global_reactive_power",xlab=" ")
dev.off()